"""Run scripts and docs bundled with downloaded generated apps."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from shared.generation.simple_ui import finalize_generated_app, finalize_generated_tests

DEFAULT_PORT = 8010

REQUIREMENTS_TXT = "\n".join(
    [
        "fastapi>=0.110",
        "uvicorn[standard]>=0.27",
        "pydantic[email]>=2.0",  # [email] pulls in email-validator, which pydantic's EmailStr needs at import time
        "tzdata",  # zoneinfo.ZoneInfo needs an IANA database; Windows and slim containers ship none
        "httpx>=0.27",
        "pytest>=8.0",
    ]
)


def refresh_artifact_sources(
    app_code: str, test_code: str, spec: dict[str, Any]
) -> tuple[str, str]:
    """Re-apply post-processors so older runs still ship a purpose-ready app."""
    app_code = finalize_generated_app(app_code, spec)
    test_code = finalize_generated_tests(test_code, spec)
    return app_code, test_code


def load_spec_from_artifacts(art_dir: Path) -> dict[str, Any]:
    spec_path = art_dir / "workflow_spec.json"
    if spec_path.exists():
        return json.loads(spec_path.read_text(encoding="utf-8"))
    return {}


def is_url_shortener_spec(spec: dict[str, Any]) -> bool:
    if spec.get("workflow_id") == "url_shortener":
        return True
    paths = {e.get("path") for e in spec.get("endpoints") or [] if isinstance(e, dict)}
    return "/shorten" in paths and any(p and "/r/" in str(p) for p in paths)


def app_title(spec: dict[str, Any]) -> str:
    return (
        spec.get("application_name")
        or spec.get("name")
        or spec.get("workflow_id")
        or "Generated App"
    )


def build_run_ps1(*, port: int = DEFAULT_PORT) -> str:
    return (
        "$ErrorActionPreference = 'Stop'\n"
        "Set-Location $PSScriptRoot\n"
        "Write-Host 'Starting generated app (not SVAGA platform)...'\n"
        f"Write-Host 'Open http://127.0.0.1:{port}/ in your browser'\n"
        "if (-not (Test-Path .venv)) { python -m venv .venv }\n"
        ".\\.venv\\Scripts\\Activate.ps1\n"
        "pip install -q -r requirements.txt\n"
        f"uvicorn app:app --reload --host 127.0.0.1 --port {port}\n"
    )


def build_readme(spec: dict[str, Any], *, port: int = DEFAULT_PORT) -> str:
    title = app_title(spec)
    desc = (spec.get("description") or "").strip()
    base = f"http://127.0.0.1:{port}"
    if is_url_shortener_spec(spec):
        use_line = (
            f"Open **{base}/** — paste a long URL and copy the short link. "
            f"Short links redirect when opened in a browser (`GET /r/{{code}}`)."
        )
    else:
        use_line = (
            f"Open **{base}/** to use the app: a form for every action, an 'Acting as' bar when the app has roles, "
            f"and a live list of records. **{base}/docs** has the raw API."
        )
    parts = [
        f"# {title}",
        "",
        "Generated by **SVAGA 3.0**. This folder is a standalone app — not the SVAGA builder (ports 8003/5303).",
        "",
    ]
    if desc:
        parts.extend([desc, ""])
    parts.extend(
        [
            "## Run (Windows)",
            "",
            "```powershell",
            "powershell -File run.ps1",
            "```",
            "",
            "Or manually:",
            "",
            "```powershell",
            "python -m venv .venv",
            ".venv\\Scripts\\Activate.ps1",
            "pip install -r requirements.txt",
            f"uvicorn app:app --host 127.0.0.1 --port {port}",
            "```",
            "",
            "## Use",
            "",
            use_line,
            "",
            "## Tests",
            "",
            "```powershell",
            "pytest test_app.py -q",
            "```",
            "",
        ]
    )
    return "\n".join(parts)


def prepare_artifacts_from_disk(art_dir: Path) -> dict[str, str]:
    """Read artifacts, refresh app/tests, return all files to place in the zip root."""
    spec = load_spec_from_artifacts(art_dir)
    app_path = art_dir / "app.py"
    test_path = art_dir / "test_app.py"
    app_code = app_path.read_text(encoding="utf-8") if app_path.exists() else ""
    test_code = test_path.read_text(encoding="utf-8") if test_path.exists() else ""
    app_code, test_code = refresh_artifact_sources(app_code, test_code, spec)

    out: dict[str, str] = {
        "app.py": app_code,
        "test_app.py": test_code,
        "requirements.txt": REQUIREMENTS_TXT,
        "run.ps1": build_run_ps1(port=DEFAULT_PORT),
        "README.md": build_readme(spec, port=DEFAULT_PORT),
    }
    for name in ("workflow_spec.json", "policy.json", "test_properties.py"):
        p = art_dir / name
        if p.exists():
            out[name] = p.read_text(encoding="utf-8")
    return out
